---
- name: download
  get_url:
    url: https://ja.wordpress.org/latest-ja.tar.gz
    dest: /tmp/wordpress.tar.gz
  
- name: make directory, if not exists
  file:
    path: "{{ wp_dir }}"
    state: directory
    recurse: yes
  become: yes

- name: unarchive
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: "{{ wp_dir }}"
    remote_src: yes
  become: yes

- name: chown
  file:
    path: "{{ wp_dir }}/wordpress"
    state: directory
    owner: nginx
    group: nginx
    mode: 0755
    recurse: yes
  become: yes

- name: wp-config.php
  template:
    src: wp-config.php.j2
    dest: "{{ wp_dir }}/wordpress/wp-config.php"
  become: yes