---
- name: module install
  dnf:
    name:
    - '@mariadb:10.3/server'
    - '@mariadb:10.3/client'
    - python3-PyMySQL
    state: present
  become: yes

- name: start mariadb service
  service:
    name: mariadb
    state: started
    enabled: yes
  become: yes

- name: set login password
  mysql_user:
    login_host: localhost
    login_user: root
    login_password:
    name: "{{ DB_LOGIN_USER }}"
    password: "{{ DB_LOGIN_PASSWORD }}"
    state: present
  no_log: true
  ignore_errors: true

- name: create database
  mysql_db:
    login_host: localhost
    login_user: "{{ DB_LOGIN_USER }}"
    login_password: "{{ DB_LOGIN_PASSWORD }}"
    name: "{{ DB_NAME }}"
    state: present
  no_log: true
  become: yes

- name: create user
  mysql_user:
    login_host: localhost
    login_user: "{{ DB_LOGIN_USER }}"
    login_password: "{{ DB_LOGIN_PASSWORD }}"
    name: "{{ DB_USER }}"
    password: "{{ DB_PASSWORD }}"
    priv: "{{ DB_NAME }}.*:ALL"
    state: present
  become: yes