---
- name: module install
  dnf:
    name:
    - python3-certbot
    - python3-certbot-nginx
    state: present
  become: yes

- name: create ssl certificate
  command: |
    certbot --nginx -n --agree-tos
    -m {{ admin_mail }} -d {{ server_name }}
  become: yes

- name: sysconfig
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: '^POST_HOOK='
    line: 'POST_HOOK="systemctl restart nginx"'
    backup: yes
  become: yes

- name: certbot-renew timer
  service:
    name: certbot-renew.timer
    state: started
    enabled: yes
  become: yes

# - name: cron job
#   cron:
#     name: certbot renew
#     minute: "0"
#     hour: "0"
#     job: certbot renew --quiet --no-self-upgrade
#   become: yes