---
- name: download
  get_url:
    url: https://ja.wordpress.org/latest-ja.tar.gz
    dest: /tmp/wordpress.tar.gz
  
- name: unarchive
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /usr/share/nginx/html
    remote_src: yes
  become: yes

- name: chown
  file:
    path: /usr/share/nginx/html
    state: directory
    owner: root
    group: root
    recurse: yes
  become: yes