---
- name: download
  get_url:
    url: https://ja.wordpress.org/latest-ja.tar.gz
    dest: /tmp/wordpress.tar.gz
  
- name: unarchive
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /usr/share/nginx/html
    remote_src: yes
  become: yes

- name: chown
  file:
    path: /usr/share/nginx/html/wordpress
    state: directory
    owner: nginx
    group: nginx
    recurse: yes
  become: yes

- name: wp-config.php
  template:
    src: wp-config.php.j2
    dest: /usr/share/nginx/html/wordpress/wp-config.php
  become: yes