---
- name: module install
  dnf:
    name: '@php:remi-7.4'
    state: present
  become: yes

- name: package install
  dnf:
    name:
    - php
    - php-devel
    - php-pear
    - php-gd
    - php-mysqlnd
    state: latest
  become: yes