---
- name: remi repository
  dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
    disable_gpg_check: yes
  become: yes

- name: module install
  dnf:
    name: '@php:remi-7.4'
    state: present
  become: yes

- name: package install
  dnf:
    name:
    - php
    - php-devel
    - php-pear
    - php-gd
    - php-mysqlnd
    state: latest
  become: yes